# Generated by Django 6.0.7 on 2026-07-10 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the click occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Visitor's IP address", null=True)),
                ('country', models.CharField(blank=True, default='', help_text='Detected country of the visitor', max_length=100)),
                ('city', models.CharField(blank=True, default='', help_text='Detected city of the visitor', max_length=100)),
                ('browser', models.CharField(blank=True, default='', help_text="Visitor's browser name", max_length=100)),
                ('browser_version', models.CharField(blank=True, default='', help_text="Visitor's browser version", max_length=50)),
                ('os', models.CharField(blank=True, default='', help_text="Visitor's operating system", max_length=100)),
                ('device', models.CharField(blank=True, default='', help_text='Device type (desktop, tablet, mobile)', max_length=50)),
                ('referrer', models.URLField(blank=True, default='', help_text='HTTP referrer header', max_length=2048)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Raw User-Agent header')),
                ('utm_source', models.CharField(blank=True, db_index=True, default='', help_text='UTM source parameter', max_length=255)),
                ('utm_medium', models.CharField(blank=True, default='', help_text='UTM medium parameter', max_length=255)),
                ('utm_campaign', models.CharField(blank=True, default='', help_text='UTM campaign parameter', max_length=255)),
                ('utm_content', models.CharField(blank=True, default='', help_text='UTM content parameter', max_length=255)),
                ('utm_term', models.CharField(blank=True, default='', help_text='UTM term parameter', max_length=255)),
                ('link', models.ForeignKey(help_text='The shortened link that was clicked', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.link')),
            ],
            options={
                'verbose_name': 'Click',
                'verbose_name_plural': 'Clicks',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['link', 'timestamp'], name='analytics_c_link_id_db0111_idx'), models.Index(fields=['timestamp'], name='analytics_c_timesta_d63331_idx'), models.Index(fields=['country'], name='analytics_c_country_957d7e_idx'), models.Index(fields=['referrer'], name='analytics_c_referre_4a4cd0_idx'), models.Index(fields=['utm_source'], name='analytics_c_utm_sou_6650bc_idx')],
            },
        ),
    ]
