# Generated by Django 6.0.6 on 2026-07-11 03:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('links', '0002_alter_link_campaign_name_alter_link_destination_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkHealth',
            fields=[
                ('link', models.OneToOneField(help_text='The link being monitored', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health', serialize=False, to='links.link')),
                ('health_score', models.PositiveSmallIntegerField(default=100, help_text='Overall health score (0-100)')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('broken', 'Broken'), ('stale', 'Stale')], db_index=True, default='healthy', help_text='Current health status', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, help_text='When the link was last scanned', null=True)),
                ('last_http_status', models.PositiveSmallIntegerField(blank=True, help_text='Last HTTP status code from destination', null=True)),
                ('redirect_count', models.PositiveSmallIntegerField(default=0, help_text='Number of redirects the destination URL goes through')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('ssl_valid', models.BooleanField(default=True, help_text='Whether the destination has a valid SSL certificate')),
                ('issues_summary', models.TextField(blank=True, default='', help_text='JSON-encoded list of issues found')),
                ('issues_count', models.PositiveSmallIntegerField(default=0, help_text='Number of active issues')),
                ('click_trend', models.CharField(choices=[('stable', 'Stable'), ('declining', 'Declining'), ('surging', 'Surging'), ('insufficient', 'Insufficient Data')], default='insufficient', help_text='Click traffic trend', max_length=20)),
                ('previous_clicks_30d', models.IntegerField(default=0, help_text='Click count 30-60 days ago')),
                ('current_clicks_30d', models.IntegerField(default=0, help_text='Click count in last 30 days')),
                ('last_destination_snapshot', models.URLField(blank=True, default='', help_text='The destination URL at last check (for detecting changes)', max_length=2048)),
                ('suggested_fix', models.TextField(blank=True, default='', help_text='Suggested fix or replacement suggestion')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the health record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the health record was last updated')),
            ],
            options={
                'verbose_name': 'Link Health',
                'verbose_name_plural': 'Link Health',
                'indexes': [models.Index(fields=['status'], name='analytics_l_status_5a54ba_idx'), models.Index(fields=['health_score'], name='analytics_l_health__232bbe_idx'), models.Index(fields=['issues_count'], name='analytics_l_issues__0909f2_idx')],
            },
        ),
    ]
