# Generated by Django 6.0.7 on 2026-07-10 18:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the link', primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(help_text='Human-readable name for the affiliate campaign', max_length=255)),
                ('destination_url', models.URLField(help_text='The full affiliate URL to redirect to', max_length=2048)),
                ('slug', models.CharField(db_index=True, help_text='Short unique identifier used in the shortened URL', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive links will not redirect')),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for the short URL', null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the link was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the link was last updated')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='links_link_slug_ecec05_idx'), models.Index(fields=['created_at'], name='links_link_created_4df6c6_idx'), models.Index(fields=['campaign_name'], name='links_link_campaig_f99200_idx')],
            },
        ),
    ]
