# Generated by Django 6.0.6 on 2026-07-11 03:17

import links.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='campaign_name',
            field=models.CharField(help_text='Human-readable name for the affiliate campaign', max_length=255, validators=[links.validators.CampaignNameValidator()]),
        ),
        migrations.AlterField(
            model_name='link',
            name='destination_url',
            field=models.URLField(help_text='The full affiliate URL to redirect to', max_length=2048, validators=[links.validators.DestinationURLValidator()]),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(db_index=True, help_text='Short unique identifier used in the shortened URL', max_length=20, unique=True, validators=[links.validators.SlugValidator(), links.validators.validate_slug_not_reserved]),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.CheckConstraint(condition=models.Q(('campaign_name', ''), _negated=True), name='links_campaign_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.CheckConstraint(condition=models.Q(('destination_url', ''), _negated=True), name='links_destination_url_not_empty'),
        ),
    ]
